### PR TITLE
Download sources from archive instead of git

### LINKED ISSUE #34: Download Qt sources from archive instead of git repo
At the origin, the idea of using the git repo was to make the download faster by only downloading the modules that will be built. However, the result is not positive. Cloning the git repo takes a lot of time and often fails due to network errors.
The package should be updated to download the sources from the archive instead.

### PR DESCRIPTION
**Pull request by ericLemanissier**
also, corrected typo from e5531edcbe5cc811b8961967b1748f4fa722fb46
fixes #34

### CODE REVIEW

**Comment by ericLemanissier** [comment]
There are less errors, but it still happens some times. I will implement a retry tomorrow...

**Comment by ericLemanissier** [comment]
Well, the XCode travis build ran 24 times in a row without problem, it didn't even hit the download exception handling and retry...

**Comment by osechet** [comment]
@ericLemanissier Thanks for your PR. As mentioned in the related issue, I think it would be better to download the whole archive from the Qt's website instead of downloading the modules one by one.

**Comment by ericLemanissier** [comment]
migrated to https://github.com/bincrafters/conan-qt

**Pull request closed without merging**
