### PR TITLE
added mingw_installer dependency

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by osechet** [comment]
I'm not really sure about this one. I don't really like the idea of forcing the build environment in the conanfile. Won't it stop people to use another toolchain?

**Comment by ericLemanissier** [comment]
In the windows+gcc configuration, this change surely does force the user. If it is not acceptable, what is the alternative solution ?
The use case is building an application which relies on Qt. The line "self.options["mingw_installer"].version = self.settings.compiler.version" can be set in the recipe of the application instead, but will this be transferred to the Qt recipe ? let's imagine the user does not want to install mingw manually, but instead rely only on conan.

**Comment by osechet** [comment]
> let's imagine the user does not want to install mingw manually, but instead rely only on conan.

A user that wants to use the Qt library, wants to build an application. He must have a build environment already setup for this. To add mingw_installer as a dependency may help people that start a project from scratch but will limit/block people that already have a build environment.

And if we follow the logic, the same should be done for Visual Studio, XCode or gcc on Linux. I don't thinks the purpose of Conan is to go that far.

**Comment by ericLemanissier** [comment]
I get your argument. There is something I don't understand in a real world use case of [conan virtual environments](http://blog.conan.io/2016/08/04/Conan-virtual-environments-Manage-your-C-and-C++-tools.html) then: It is not possible to use both an environment and a library at the same time ?

**Comment by ericLemanissier** [comment]
Ok, I was missing the profile part, and the fact that they can be stored next to the conan recipe. Thanks !

**Pull request closed without merging**
