### PR TITLE
Testing/5.7.0

### PR DESCRIPTION
**Pull request by cpace6**
Sorry for the repeat PRs, I realized I forgot to update a few occurrences of the old version number

### CODE REVIEW

**Comment by osechet** [comment]
To fix the issue on Linux, you have to add the following lines to the test_package's CMakeLists.txt:
* Just after the `add_executable(helloworld main.cpp)` line:
```
target_compile_features(helloworld PRIVATE cxx_nullptr)
```

* Just after the `add_executable(helloworld2 main.cpp)` line:
```
target_compile_features(helloworld2 PRIVATE cxx_nullptr)
```

It will activate the support for c++11.

**Comment by osechet** [comment]
For the Windows build, it's an issue I didn't have the time to investigate: git needs the `sh.exe` executable to exist in order to run the submodule command. However, cmake refuses to work if it finds `sh.exe` in `PATH`. I made a very ugly fix (in 5.6.2 branch) that should help for the moment.

**Comment by cpace6** [comment]
Thank you for the feedback, I made those changes.

**Comment by osechet** [comment]
I merged your PR. Don' t pay attention to the "Revert": I made a mistake when merging and I had to do manual changes.
Thanks for your help.

**Pull request merged**
